### ISSUE TITLE
Priority item: Phase1 Poc deployment to Sandbox

### ISSUE THREAD

**Issue by vijayg10** [sp-convergence/mojaloop-openhim-fhir-poc#1]
## **Goal**:
`As a` stakeholder

`I want to` deploy the PoC from phase1 (G2B using OpenHIM and mojaloop thirdparty transfer) to sandbox
  
`so that` I can use it for demonstration purposes

**Acceptance Criteria**:
- [x] Phase1 PoC is working on sandbox
- [x] Phase2 Poc is also working without any port conflicts with phase1 PoC
- [x] Documentation is provided with links and how to use

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [x] Deploy the PoC to sandbox
  - [x] Refactored the docker stack to simplify the deployment and to enable the remote deployments
- [x] Make sure everything is working and prepare instructions to test
- [x] Make sure the phase2 PoC is also working without any conflicts
- [x] Pass the information with links and documentation to the team

**Done**
- [x] Acceptance Criteria pass
- [x] Documentation is updated

## **Pull Requests**:
- NA

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @vijayg10 
- QA/Review: TBC

**Comment by vijayg10** [comment]
PoC is deployed in the sandbox. Waiting for the ports to be opened by AH team to test.
